#!/bin/bash

PIDFILE="/tmp/wl-screenrec.pid"

if [ -f "$PIDFILE" ]; then
    # Stop recording
    /usr/bin/kill $(cat "$PIDFILE") 2>/dev/null
    rm "$PIDFILE"
    /usr/bin/notify-send "Screen Recording" "Recording stopped"
else
    # Start recording
    GEOMETRY=$(/usr/bin/slurp 2>/dev/null)
    if [ $? -eq 0 ]; then
        if [ -n "$GEOMETRY" ]; then
            # Record selected area
            /usr/bin/wl-screenrec -g "$GEOMETRY" -f "$HOME/Videos/recording-$(date +%Y%m%d-%H%M%S).mp4" &
        else
            # Record full screen
            /usr/bin/wl-screenrec -f "$HOME/Videos/recording-$(date +%Y%m%d-%H%M%S).mp4" &
        fi
        echo $! > "$PIDFILE"
        /usr/bin/notify-send "Screen Recording" "Recording started"
    fi
fi